"""db sync

Revision ID: 276ee2b15b38
Revises: 47fcc46f7380
Create Date: 2020-02-10 12:22:40.405916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '276ee2b15b38'
down_revision = '47fcc46f7380'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'employee_function_link', 'functions', ['employee_function'], ['function'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_index(op.f('ix_functions_finance_function'), 'functions', ['finance_function'], unique=True)
    op.create_foreign_key(None, 'registered_users', 'functions', ['function'], ['function'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'registered_users', type_='foreignkey')
    op.drop_index(op.f('ix_functions_finance_function'), table_name='functions')
    op.drop_constraint(None, 'employee_function_link', type_='foreignkey')
    # ### end Alembic commands ###
