"""adding usermixin from flask_login to registered users class

Revision ID: 372abda15300
Revises: 3cee229d951e
Create Date: 2019-12-06 10:49:23.807309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '372abda15300'
down_revision = '3cee229d951e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
