"""added column to functions for finance category matching

Revision ID: 47fcc46f7380
Revises: 64e1e03b4a04
Create Date: 2020-02-10 12:11:05.443373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47fcc46f7380'
down_revision = '64e1e03b4a04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('functions', sa.Column('finance_function', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('functions', 'finance_function')
    # ### end Alembic commands ###
