"""initial db generation

Revision ID: 57be6decce4d
Revises: 
Create Date: 2020-01-31 12:20:04.544949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57be6decce4d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'employee_function_link', 'functions', ['employee_function'], ['function'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'registered_users', 'functions', ['function'], ['function'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'registered_users', type_='foreignkey')
    op.drop_constraint(None, 'employee_function_link', type_='foreignkey')
    # ### end Alembic commands ###
