"""initial db generation

Revision ID: 64e1e03b4a04
Revises: 57be6decce4d
Create Date: 2020-01-31 13:46:44.436924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64e1e03b4a04'
down_revision = '57be6decce4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', name='PK_department_id')
    )
    op.create_index(op.f('ix_departments_department'), 'departments', ['department'], unique=True)
    op.create_table('employee_numbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='PK_num_id'),
    sa.UniqueConstraint('number', name='UQ_num_num')
    )
    op.create_table('functions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('function', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', name='PK_func_id')
    )
    op.create_index(op.f('ix_functions_function'), 'functions', ['function'], unique=True)
    op.create_table('programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('comments', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='PK_pgm_id'),
    sa.UniqueConstraint('name', name='UQ_pgm_name')
    )
    op.create_table('employee_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_last', sa.String(length=50), nullable=False),
    sa.Column('name_first', sa.String(length=50), nullable=False),
    sa.Column('job_title', sa.String(length=50), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('job_code', sa.String(length=10), nullable=False),
    sa.Column('date_start', sa.Date(), nullable=False),
    sa.Column('date_end', sa.Date(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('employee_number_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_number_number'], ['employee_numbers.number'], name='FK_emp_num'),
    sa.PrimaryKeyConstraint('id', name='PK_emp_data_id')
    )
    op.create_index(op.f('ix_employee_data_name_first'), 'employee_data', ['name_first'], unique=False)
    op.create_index(op.f('ix_employee_data_name_last'), 'employee_data', ['name_last'], unique=False)
    op.create_table('employee_function_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_number', sa.Integer(), nullable=True),
    sa.Column('employee_function', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['employee_function'], ['functions.function'], name='FK_func_link_func', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_number'], ['employee_numbers.number'], name='FK_func_link_emp_num'),
    sa.PrimaryKeyConstraint('id', name='PK_func_link_id')
    )
    op.create_table('employee_program_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_number', sa.Integer(), nullable=True),
    sa.Column('employee_program', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['employee_number'], ['employee_numbers.number'], name='FK_pgm_link_emp_num'),
    sa.ForeignKeyConstraint(['employee_program'], ['programs.name'], name='FK_pgm_link_pgm', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='PK_pgm_link_id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('date_start', sa.Date(), nullable=False),
    sa.Column('date_end', sa.Date(), nullable=True),
    sa.Column('program_type', sa.String(length=50), nullable=True),
    sa.Column('program_name', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['program_name'], ['programs.name'], name='FK_proj_pgm', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='PK_proj_id'),
    sa.UniqueConstraint('name', name='UQ_proj_name')
    )
    op.create_table('registered_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('employee_number_number', sa.Integer(), nullable=True),
    sa.Column('function', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['employee_number_number'], ['employee_numbers.number'], name='FK_account_emp_num'),
    sa.ForeignKeyConstraint(['function'], ['functions.function'], name='FK_account_func'),
    sa.PrimaryKeyConstraint('id', name='PK_account_id')
    )
    op.create_index(op.f('ix_registered_users_username'), 'registered_users', ['username'], unique=True)
    op.create_table('charge_numbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('charge_number', sa.String(length=50), nullable=False),
    sa.Column('project_name', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['project_name'], ['projects.name'], name='FK_chg_proj', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='PK_chg_id'),
    sa.UniqueConstraint('charge_number', name='UQ_chg_num')
    )
    op.create_table('resource_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('sub_period', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=False),
    sa.Column('hours', sa.Float(), nullable=False),
    sa.Column('project_name', sa.String(length=50), nullable=True),
    sa.Column('employee_number_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_number_number'], ['employee_numbers.number'], name='FK_rsrc_emp_num'),
    sa.ForeignKeyConstraint(['project_name'], ['projects.name'], name='FK_rsrc_proj', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='PK_rsrc_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resource_entries')
    op.drop_table('charge_numbers')
    op.drop_index(op.f('ix_registered_users_username'), table_name='registered_users')
    op.drop_table('registered_users')
    op.drop_table('projects')
    op.drop_table('employee_program_link')
    op.drop_table('employee_function_link')
    op.drop_index(op.f('ix_employee_data_name_last'), table_name='employee_data')
    op.drop_index(op.f('ix_employee_data_name_first'), table_name='employee_data')
    op.drop_table('employee_data')
    op.drop_table('programs')
    op.drop_index(op.f('ix_functions_function'), table_name='functions')
    op.drop_table('functions')
    op.drop_table('employee_numbers')
    op.drop_index(op.f('ix_departments_department'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
