"""changing function relation in employee data

Revision ID: 6f54b70af268
Revises: 372abda15300
Create Date: 2019-12-09 10:46:55.494213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f54b70af268'
down_revision = '372abda15300'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('FK__employee___assig__532343BF', 'employee_data', type_='foreignkey')
    op.create_foreign_key(None, 'employee_data', 'functions', ['assigned_function'], ['function'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employee_data', type_='foreignkey')
    op.create_foreign_key('FK__employee___assig__532343BF', 'employee_data', 'functions', ['assigned_function'], ['id'])
    # ### end Alembic commands ###
