"""changing function relation in employee data

Revision ID: 9f9355b5d63e
Revises: 6f54b70af268
Create Date: 2019-12-09 10:59:23.101098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f9355b5d63e'
down_revision = '6f54b70af268'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'employee_data', 'functions', ['assigned_function'], ['function'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employee_data', type_='foreignkey')
    # ### end Alembic commands ###
