"""changing function relation in employee data

Revision ID: dad7b5a8ad2d
Revises: 9f9355b5d63e
Create Date: 2019-12-09 11:03:32.742478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dad7b5a8ad2d'
down_revision = '9f9355b5d63e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_last', sa.String(length=50), nullable=False),
    sa.Column('name_first', sa.String(length=50), nullable=False),
    sa.Column('job_title', sa.String(length=50), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('job_code', sa.String(length=10), nullable=False),
    sa.Column('date_start', sa.Date(), nullable=False),
    sa.Column('date_end', sa.Date(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('employee_number', sa.Integer(), nullable=True),
    sa.Column('assigned_programs', sa.String(length=50), nullable=True),
    sa.Column('assigned_function', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['assigned_function'], ['functions.function'], ),
    sa.ForeignKeyConstraint(['assigned_programs'], ['programs.name'], ),
    sa.ForeignKeyConstraint(['employee_number'], ['employee_numbers.number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_data_name_first'), 'employee_data', ['name_first'], unique=False)
    op.create_index(op.f('ix_employee_data_name_last'), 'employee_data', ['name_last'], unique=False)
    op.create_foreign_key(None, 'functions', 'employee_numbers', ['employee_numbers'], ['number'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'functions', type_='foreignkey')
    op.drop_index(op.f('ix_employee_data_name_last'), table_name='employee_data')
    op.drop_index(op.f('ix_employee_data_name_first'), table_name='employee_data')
    op.drop_table('employee_data')
    # ### end Alembic commands ###
