"""updating programs columns for new link table

Revision ID: dd6879753b68
Revises: fd6051474522
Create Date: 2020-03-25 11:11:12.801651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd6879753b68'
down_revision = 'fd6051474522'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resource_entries_temp')
    op.create_foreign_key(None, 'employee_function_link', 'functions', ['employee_function'], ['function'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_index(op.f('ix_functions_finance_function'), 'functions', ['finance_function'], unique=True)
    op.create_foreign_key(None, 'registered_users', 'functions', ['function'], ['function'])
    op.alter_column('resource_entries', 'hours',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               nullable=False)
    op.create_foreign_key(None, 'resource_entries', 'functions', ['function_name'], ['function'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resource_entries', type_='foreignkey')
    op.alter_column('resource_entries', 'hours',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               nullable=True)
    op.drop_constraint(None, 'registered_users', type_='foreignkey')
    op.drop_index(op.f('ix_functions_finance_function'), table_name='functions')
    op.drop_constraint(None, 'employee_function_link', type_='foreignkey')
    op.create_table('resource_entries_temp',
    sa.Column('uid', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('year', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('period', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('sub_period', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('quarter', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('month', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('hours', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('charge_number', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('function_name', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
