"""changed resource_entry hours to decimal

Revision ID: ea8e8170e876
Revises: 31d489546784
Create Date: 2020-03-10 11:11:11.010011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea8e8170e876'
down_revision = '78433d3fab89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resource_entries', 'hours', existing_type=sa.FLOAT, type_=sa.DECIMAL(precision=10, scale=2), nullable=[bool])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resource_entries', 'hours', existing_type=sa.DECIMAL(precision=10, scale=2), type_=sa.FLOAT, nullable=[bool])
    # ### end Alembic commands ###
