"""adding program <> project link table

Revision ID: fd6051474522
Revises: ea8e8170e876
Create Date: 2020-03-25 10:30:05.767352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd6051474522'
down_revision = 'ea8e8170e876'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('program_project_link',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('program_name', sa.String(length=50), nullable=True),
    sa.Column('project_name', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['program_name'], ['programs.name'], ),
    sa.ForeignKeyConstraint(['project_name'], ['projects.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('program_project_link')
    # ### end Alembic commands ###
