"""generating tables

Revision ID: ff11d28c68dc
Revises: e1f7078d38af
Create Date: 2019-12-04 15:33:53.164198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff11d28c68dc'
down_revision = 'e1f7078d38af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charge_numbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('charge_number', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('charge_number')
    )
    op.create_table('employee_numbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('functions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('function', sa.String(length=50), nullable=False),
    sa.Column('employee_numbers', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_numbers'], ['employee_numbers.number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_functions_function'), 'functions', ['function'], unique=True)
    op.create_table('programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('employee_numbers', sa.Integer(), nullable=True),
    sa.Column('charge_number', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['charge_number'], ['charge_numbers.charge_number'], ),
    sa.ForeignKeyConstraint(['employee_numbers'], ['employee_numbers.number'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('registered_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('employee_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_number'], ['employee_numbers.number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registered_users_username'), 'registered_users', ['username'], unique=True)
    op.create_table('employee_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_first', sa.String(length=50), nullable=False),
    sa.Column('name_last', sa.String(length=50), nullable=False),
    sa.Column('job_title', sa.String(length=50), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('job_code', sa.String(length=10), nullable=False),
    sa.Column('date_start', sa.Date(), nullable=False),
    sa.Column('date_end', sa.Date(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('employee_number', sa.Integer(), nullable=True),
    sa.Column('assigned_programs', sa.String(length=50), nullable=True),
    sa.Column('assigned_function', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_function'], ['functions.id'], ),
    sa.ForeignKeyConstraint(['assigned_programs'], ['programs.name'], ),
    sa.ForeignKeyConstraint(['employee_number'], ['employee_numbers.number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_data_name_first'), 'employee_data', ['name_first'], unique=False)
    op.create_index(op.f('ix_employee_data_name_last'), 'employee_data', ['name_last'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('date_start', sa.Date(), nullable=False),
    sa.Column('date_end', sa.Date(), nullable=True),
    sa.Column('program_type', sa.String(length=50), nullable=True),
    sa.Column('parent_program', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['parent_program'], ['programs.name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('resource_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('sub_period', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=False),
    sa.Column('hours', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('employee_number', sa.Integer(), nullable=True),
    sa.Column('project', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['employee_number'], ['employee_numbers.number'], ),
    sa.ForeignKeyConstraint(['project'], ['projects.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resource_entries')
    op.drop_table('projects')
    op.drop_index(op.f('ix_employee_data_name_last'), table_name='employee_data')
    op.drop_index(op.f('ix_employee_data_name_first'), table_name='employee_data')
    op.drop_table('employee_data')
    op.drop_index(op.f('ix_registered_users_username'), table_name='registered_users')
    op.drop_table('registered_users')
    op.drop_table('programs')
    op.drop_index(op.f('ix_functions_function'), table_name='functions')
    op.drop_table('functions')
    op.drop_table('employee_numbers')
    op.drop_table('charge_numbers')
    # ### end Alembic commands ###
